### PR TITLE
Deserialize with serde

### PR DESCRIPTION
**Pull request by riley-harper**
This PR creates a new module named `json_schema` which contains types for deserializing Abacus requests. I chose names that mirror the names in src/request.rs. If this is confusing, we could change them. The main struct in the new module is `json_schema::AbacusRequest`, which you can use like this:

```rust
let json_str = "...";
let request: AbacusRequest = serde_json::from_str(json_str).unwrap();
```

I've integrated the `json_schema` module with the `request::Abacus::from_json()` function. `from_json()` parses the input string into a `json_schema::AbacusRequest`, then does transformations to apply metadata and create a context for the request. This has the nice effect of separating out the parsing from the metadata application. It also explicitly documents the input format in a single module. One disadvantage of this approach is that we now have duplicated code between `json_schema` structs and their applied-metadata counterpart structs.

Here are some thoughts and possible future improvements:

- `json_schema` is probably not a great name for the module, since it can parse other formats as well. Maybe `input_schema` would be better?
- I am not sure what the type of `RequestVariable.attached_variable_pointer` is, so I have left it as unit for now.
- Should `RequestVariable.general_detailed_selection` be an `Option<String>`, or just a `String`? In the examples I've seen, it looks like the front-end might be sending us either `"G"` or `""`, so it would just be a `String`. Actually at this rate, we should probably just create an enum for it in `json_schema` and parse it there. Something like this?

```rust
enum GeneralDetailedSelection {
    General,
    Detailed,
}
```

- Similarly, should we pull the `request::OutputFormat` enum into `json_schema` and parse the `output_format` field there?
- Last thought: since `json_schema::AbacusRequest` is somewhat ephemeral and gets consumed as part of other code, we could replace the `String`s in its types with `&'a str`s, borrowing from the deserializer for efficiency. We don't really need to do this now but if we ever need to parse many requests very quickly or some very large requests, then that would be an option.

### CODE REVIEW

**Comment by riley-harper** [comment]
Serialization is not working correctly for the `CategoryBin` and `RequestCaseSelection` because we are using intermediate structs for those. I am working on fixing that and adding a round-trip test.

**Comment by ccdavis** [comment]
* Since the json_schema module only defines a tabulation input schema and not a request schema (which I'm planning on) something like 'json_tabulation_schema' could make sense. Or 'input_schema_tabulation'. There's some notion of going from least to most specific in multi part names on these kinds of naming schemes but the significance of each part isn't obvious.
* attached_variable_pointer is a null or string in the JSON. In the struct it could be an IpumsVariable or a name of a variable or an id. unit is fine for the moment, we can update if we do extracts which is where the attached variables are used.
*  The general_detailed field should probably be a real type with an enum. It comes in as 'G' or '' or null -- a bit messy I think It can only ever be GeneralDetailed::General or GeneralDetailed::Detailed, where Detailed is the default.
*  The OutputFormat enum will be used by any binary asking for data so I think it makes sense to be in the 'request' module.

Overall this all looks good

Note in my branch I've just added support for 'case_select_logic' and 'case_select_individual' fields on the main request. At the moment I'm just hard-coding the values in the DataRequest impl for SimpleRequest and AbacusRequest. We may need to change the case_select_logic at some point to take a value from the JSON.

**Review by ccdavis — APPROVED** [review]
All right, I understand it. Looks good.

**Comment by ccdavis** [comment]
I think we should merge this once you've made any updates based on my comments. Merging with the bits with the case_select_logic and case_select_individual can be done later on.

**Comment by riley-harper** [comment]
Ok, I've made the updates and I'll go ahead and merge this in. All the tests are passing.

Edit: I do not have a merge button, but feel free to merge this whenever.

**Review by ccdavis — APPROVED** [review]

**Pull request merged**
